services:
  postgres:
    container_name: my-postgres
    build: ./database/
    restart: on-failure
    env_file:
      - .env
    networks:
      - nest_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  nest_network:
