services:
  node:
    build: .
    restart: always
    networks:
      - nest_network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    env_file:
      - .env
  postgres:
    build: ./database/
    restart: always
    networks:
      - nest_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data

networks:
  nest_network:
