version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    # prettier-ignore
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
